language: c++

cache:
  ccache: true

addons:
  apt:
    update: true
    packages:
      - clang
      - clang-format
      - llvm
      - llvm-dev
      - lcov
      - ruby
      - gcc-12
      - g++-12

env:
  global:
    - CMAKE_C_COMPILER_LAUNCHER=ccache
    - CMAKE_CXX_COMPILER_LAUNCHER=ccache

jobs:
  include:
    - name: "Static Analysis"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS=ON .
      script:
        - cmake --build . --config Debug --parallel 3

    - name: "Sanitizer"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - mkdir build-address
        - pushd build-address
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Address ..
        - cmake --build . --config Debug --parallel 3
        - popd
        - mkdir build-stack
        - pushd build-stack
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Stack ..
        - cmake --build . --config Debug --parallel 3
        - popd
        - mkdir build-thread
        - pushd build-thread
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Thread ..
        - cmake --build . --config Debug --parallel 3
        - popd
      script:
        - pushd build-address/tests
        - ctest -j1 --output-on-failure
        - popd
        - pushd build-stack/tests
        - ctest -j1 --output-on-failure
        - popd
        - pushd build-thread/tests
        - ctest -j1 --output-on-failure

    - name: "Coverage"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      install:
        - sudo gem install coveralls-lcov
      before_script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON ..
      script:
        - cmake --build . --config Debug --parallel 3 --target coverage
      after_success:
        - coveralls-lcov --repo-token $COVERALLS_REPO_TOKEN --service-name travis-pro --service-job-id $TRAVIS_JOB_ID ./coverage.info

    - name: "GCC Unit Tests"
      os: linux
      dist: jammy
      env:
        - CC=gcc-12
        - CXX=g++-12
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - cmake --build . --config Release --parallel 3
      script:
        - cd tests
        - ctest -j3 --output-on-failure

    - name: "Clang Unit Tests and Formatting"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - cmake --build . --config Release --parallel 3
      script:
        - cmake --build . --config Release --parallel 3 --target format.check
        - cd tests
        - ctest -j3 --output-on-failure

notifications:
  slack:
    secure: O4TvBEmY6TkfIFlcXQ0Xgp7TdhGW1bTMAPgX1er9zD628GF8eM/vMzEsCVoD03ISa5z3zFaG5cTiAfycbIoUdeGp2FsczXxOQ+4iI6uVCG4tL1BumQ7DOMTcFU27YDWjdlDLbvQP+Uf/ydbgbT9Ili7qEeDR+6TZw6/dKZX0Lm4J1rRnzoUzU/7km4wNVHWLQuq3nSRbSVH1ae00fifhCwUyvshKK0oSyNDPnpDx+qtDZxbmcalx2DYTxM728P6D8WSpNpu4g/7kLGuFHCq6oleWwkx8KRBRoOOxFK8RRC6a2ss5wye4jJa0Qn6vUtgkn+n3sDJ6dDLra8uzdM1pAuNCEphdgHuPo2SkjdZfxg+y1j6RLs4H3BSlIRrjcNmCCl8wOOiq0dUAyJ9vDQIav9Z5te0uupuKrQI3y5OeSczU+ZAIxojflfltIdsR0roqLZVpmXLJnvlQmb7ewkgJvgxggUPyojlabmjBcIbHMTH6vZeQhznICPdt+/ufeC9DpxY6xMzBXN8IPBbAadJ5P3yc7j2nb+yHxhq8mubyj93hbNDXomYmSKlGwgKje2RthjdXd7tSrx+H81K7wMOk6Ehmb0uGF2kbgz2Iibc7CA6xDn6TgW4yj2FDp3oVoa5V2tQaWLoP3IQlBXgpiwahRCW5rM8bCW+ierGHmlNT824=
    on_success: never
